// src/stories/extensions/button.svelte
<script>
import SvelteSummernoteLite, { createSummernoteButton } from 'src/summernote/SvelteSummernoteLite.svelte'
import MyButton from './MyButton.svelte';

</script>

<style>
.container {
  padding: 20px 40px;
}
</style>

<div class="container">
      <h1>Define Svelte Button</h1>

      <pre>{`

<script>
  // MyButton.svelte 
  import { onMount, onDestroy } from 'svelte';
  export let text; 
  export let context;

  function handleChangeValue (_, content) {
    text = content
  }

  onMount(() => {
    context.$note.on('summernote.change', handleChangeValue) 
  })

  onDestroy(() => {
      context.$note.off('summernote.change', handleChangeValue) 
  })
</script>

<span>{text}</span>      
      
      `}</pre>

      <pre>{`
        import SvelteSummernoteLite, { createSummernoteButton } from 'src/summernote/SvelteSummernoteLite';
        import MyButton from './MyButton.svelte';

        <SvelteSummernoteLite id="sample" 
            toolbar={[
              ['group', ['hello']]
            ]}
            buttons={{
              hello: createSummernoteButton({
                element: MyButton,
                props: {
                  text: 'sample'
                },
                container: 'body',
                tooltip: 'yellow'
              })
            }}  
          />
      `}</pre>

<SvelteSummernoteLite id="sample" 
  toolbar={[
    ['group', ['hello']]
  ]}
  buttons={{
    hello: createSummernoteButton({
      element: MyButton,
      props: {
        text: 'sample'
      },
      container: 'body',
      tooltip: 'yellow'
    })
  }}  
/>

</div>

// src/stories/extensions/button.tsx
import React, { useState, useEffect } from 'react'; 
import { withKnobs } from "@storybook/addon-knobs"
import { defaultStyle } from "../util"
import SvelteSummernoteLite, { createSummernoteButton } from 'src/summernote/SvelteSummernoteLite';
import { SummernoteButtonProps } from 'types';

function MyButton(props: SummernoteButtonProps) {

  const [value, setValue] = useState('my button');
  const div = document.createElement('div');

  function handleChangeValue (_: any, content: string) {
    div.innerHTML = content;
    setValue(div.textContent);
  }

  useEffect(() => {
    props.context.$note.on('summernote.change', handleChangeValue) 
    return () => {
      props.context.$note.off('summernote.change', handleChangeValue) 
    }
  }, [])

return <span onClick={() => alert('aa')}>{value} - {props.title}</span>
}

export const ButtonExtension = () => {
    return (
      <div style={defaultStyle}>
        <h1>Define React Button</h1>
      <pre>{`
        import SvelteSummernoteLite, { createSummernoteButton } from 'src/summernote/SvelteSummernoteLite';

                
        function MyButton(props: SummernoteButtonProps) {

          const [value, setValue] = useState('my button');
          const div = document.createElement('div');

          function handleChangeValue (_: any, content: string) {
            div.innerHTML = content;
            setValue(div.textContent);
          }

          useEffect(() => {
            props.context.$note.on('summernote.change', handleChangeValue) 
            return () => {
              props.context.$note.off('summernote.change', handleChangeValue) 
            }
          }, [])

          return <span onClick={() => alert('aa')}>{value} - {props.title}</span>
        }

        <SvelteSummernoteLite id="sample" 
            toolbar={[
              ['group', ['hello']]
            ]}
            buttons={{
              hello: createSummernoteButton({
                element: MyButton,
                props: {
                  title: 'sample'
                },
                container: 'body',
                tooltip: 'yellow'
              })
            }}  
          />
      `}</pre>
          <SvelteSummernoteLite id="sample" 
            toolbar={[
              ['group', ['hello']]
            ]}
            buttons={{
              hello: createSummernoteButton({
                element: MyButton,
                props: {
                  title: 'sample'
                },
                container: 'body',
                tooltip: 'yellow'
              })
            }}  
          />
      </div>
    )
  }
  
  ButtonExtension.story = {
    name: 'react button',
    decorators: [withKnobs],
  }
